"""Wiki contract v2 vocabularies and required field sets."""

from __future__ import annotations

SOURCE_TYPES = frozenset(
    {
        "official-product-page",
        "official-technical-specification",
        "official-user-manual",
        "official-service-manual",
        "official-maintenance-guide",
        "official-safety-notice",
        "official-recall",
        "official-firmware-release-note",
        "official-software-release-note",
        "official-knowledge-base",
        "official-source-code",
        "standard",
        "regulatory-guidance",
        "sds",
        "tds",
        "primary-research",
        "systematic-review",
        "controlled-experiment",
        "technical-method",
        "official-forum",
        "community-report",
        "discovery-only",
        "manufacturer-product-listing",
        "unknown",
    }
)

ID_REFERENCE_FIELDS: tuple[str, ...] = (
    "sources",
    "related",
    "prerequisites",
    "supersedes",
    "materials",
    "printers",
    "slicers",
    "settings",
    "symptoms",
    "causes",
    "tests",
    "fixes",
    "hazards",
    "components",
    "firmware",
    "manufacturers",
    "families",
    "revisions",
)

PRINTER_REQUIRED_FIELDS: tuple[str, ...] = (
    "manufacturer_id",
    "model_name",
    "aliases_pt_br",
    "aliases_en",
    "regions",
    "lifecycle",
    "lifecycle_observed_at",
    "availability_evidence",
    "coverage_level",
    "technology",
    "process",
    "knowledge_status",
    "evidence_status",
    "confidence",
    "last_reviewed",
    "review_cycle",
    "sources",
    "related",
    "prerequisites",
    "supersedes",
    "tags",
)

DOCUMENTED_DOD_MARKERS: tuple[str, ...] = (
    "## Identidade",
    "## Lifecycle",
    "## Especificações",
    "## Tecnologia",
    "## Manuais",
    "## Hardware",
    "## Software",
    "## Firmware",
    "## Slicer",
    "## Materiais",
    "## Manutenção",
    "## Segurança",
    "## Known issues",
    "## Fontes",
    "## Lacunas",
)
